### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by otofu-square** [otofu-square/docker-github-nippou#1]
- [ ] Push Docker Hub
- [ ] Ride on [whalebrew](https://github.com/bfirsh/whalebrew)
- [ ] Improve `bin/github-nippou` ( Get the token & user from git or environment values )
- [ ] Improve `Dockerfile` to use `CMD`
- [ ] Add `LICENSE` file
- [ ] Add `README.md` file
